"""
The Witness Network – Ticket API Routes
=========================================
Endpoints for querying, filtering, and inspecting anomaly tickets
generated by the Three-Way Arbitration Engine.

GET  /api/tickets              → List tickets (with filters)
GET  /api/tickets/summary      → Aggregated dashboard stats
GET  /api/tickets/{ticket_id}  → Single ticket detail
"""

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.models.anomaly import (
    AnomalyDecision,
    AnomalyEventResponse,
    Severity,
)
from app.services.ticket_service import (
    list_tickets,
    get_ticket_by_id,
    get_ticket_summary,
)


router = APIRouter(prefix="/api/tickets", tags=["Tickets"])


# ── GET /api/tickets ─────────────────────────────────────────────────

@router.get(
    "",
    response_model=dict,
    summary="List anomaly tickets",
    description=(
        "Returns paginated anomaly tickets with optional filters "
        "for station, decision type, and severity."
    ),
)
async def list_all_tickets(
    station_id: Optional[str] = Query(
        None, description="Filter by station ID"
    ),
    decision: Optional[AnomalyDecision] = Query(
        None, description="Filter by arbitration decision"
    ),
    severity: Optional[Severity] = Query(
        None, description="Filter by severity level"
    ),
    limit: int = Query(50, ge=1, le=200, description="Max results"),
    offset: int = Query(0, ge=0, description="Pagination offset"),
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Query anomaly tickets with optional filters and pagination."""
    tickets = await list_tickets(
        db=db,
        station_id=station_id,
        decision=decision,
        severity=severity,
        limit=limit,
        offset=offset,
    )
    return {
        "count": len(tickets),
        "tickets": [t.model_dump() for t in tickets],
    }


# ── GET /api/tickets/summary ─────────────────────────────────────────

@router.get(
    "/summary",
    summary="Get ticket summary statistics",
    description="Returns aggregated counts grouped by decision type and severity.",
)
async def ticket_summary(
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Dashboard-friendly aggregated ticket stats."""
    summary = await get_ticket_summary(db)
    return summary


# ── GET /api/tickets/{ticket_id} ─────────────────────────────────────

@router.get(
    "/{ticket_id}",
    response_model=AnomalyEventResponse,
    summary="Get a single ticket by ID",
)
async def get_single_ticket(
    ticket_id: int,
    db: AsyncSession = Depends(get_db),
) -> AnomalyEventResponse:
    """Retrieve detailed information for a specific anomaly ticket."""
    ticket = await get_ticket_by_id(ticket_id, db)

    if ticket is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Ticket with id={ticket_id} not found",
        )

    return ticket
